version: '3.5'

services:

  # Banco de dados
  postgres:
    container_name: postgres_lbd
    image: postgres
    build: 
      context: './postgres'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      PGDATA: /data
    volumes:
       - postgresVolume:/data
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  #Admin do banco de dados
  pgadmin:
    container_name: pgadmin_lbd
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-80}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgresVolume:
    pgadmin: